#pragma once

#define IDC_STATIC      -1
#define IDC_MYICON      2
#define IDS_APP_TITLE   100
#define IDS_OPEN        101
#define IDD_ABOUTBOX    102
#define IDC_MFVE        103
#define IDI_SMALL       104
#define IDD_ADDTRANSFORM    105
#define IDC_TRANSFORMLIST   106
#define IDB_TRANSPORTTOOL   107
#define IDD_ENCODEOPTIONS   108
#define IDC_CBR             109
#define IDC_VBR             110
#define IDC_BOXLABEL        111
#define IDC_VALUE           112
#define IDD_METADATA        113
#define IDC_FILENAME        114
#define IDC_FILESIZE        115
#define IDC_FRAMESIZE       116
#define IDC_FPS             117
#define IDC_PAR             118
#define IDC_AVGBITRATE      119
#define IDC_SUBTYPE         120
#define IDC_FRAMECOUNT      121
#define IDC_KEYFRAMECOUNT   122
#define IDC_INTERLACEMODE   123
#define IDC_DURATION        124
#define IDC_MIMETYPE        125
#define IDC_SUBTYPEAUDIO    126
#define IDC_NUMCHANNELS     127
#define IDC_AVGBYTESSEC     128
#define IDC_BLOCKALIGN      129
#define IDC_BITSPERSAMPLE   130
#define IDC_SAMPLESPERSEC   131
#define IDC_TRANSFORMDESC   132
#define IDC_CHANGEFRAMERATE 133
#define IDC_FRAMERATE       134
#define IDB_MAINTOOL        135

#define ID_OPEN         1000
#define ID_SAVE         1001
#define ID_ADDTRANSFORM 1002
#define ID_PLAYOUTPUT   1003
#define ID_PLAYPREVIEW  1004
#define ID_STOP		1005
#define ID_ENCODEOPTIONS    1006
#define ID_NEXTKEYFRAME     1007
#define ID_PREVKEYFRAME     1008
#define ID_PROPERTIES       1009
#define ID_GO_BEGINNING     1010
#define ID_GO_END           1011
#define ID_ADDAUDIOTRANSFORM 1012

#define IDS_ERROR_INITIALIZING      5000
#define IDS_ERROR_SEEKING           5001
#define IDS_ERROR_GENERIC           5002
#define IDS_ERROR_WINDOW_CREATION   5003
#define IDS_ERROR_LOAD_SOURCE       5004
#define IDS_ERROR_WRITE_OUTPUT      5005
#define IDS_ERROR_ADD_TRANSFORM     5006
#define IDS_ERROR_PLAYBACK          5007
#define IDS_ERROR_PLAYBACK_PREVIEW  5008
#define IDS_VIDEO_TRANSFORMS        5009
#define IDS_AUDIO_TRANSFORMS        5010
#define IDS_FILTER_MEDIA_FILES      5011
#define IDS_SELECT_SOURCE           5012
#define IDS_SELECT_SINK             5013
#define IDS_REASON                  5014
#define IDS_FRAME_INFO_KEY          5015
#define IDS_FRAME_INFO              5016
#define IDS_PLAYBACK_INFO           5017
#define IDS_ENCODING_INFO           5018
#define IDS_ERROR_ADD_TRANSFORM_MAX 5019
